import type { ThemeConfig } from "antdv-next";
import { theme } from "antdv-next";

export const shadcnPalette = {
  zinc: {
    50: "#fafafa",
    100: "#f4f4f5",
    200: "#e4e4e7",
    300: "#d4d4d8",
    400: "#a1a1aa",
    500: "#737373",
    600: "#525252",
    700: "#404040",
    800: "#262626",
    900: "#18181b",
  },
  white: "#ffffff",
  success: {
    base: "#22c55e",
    hover: "#16a34a",
    active: "#15803d",
    bg: "#f0fdf4",
    bgHover: "#dcfce7",
    border: "#bbf7d0",
    borderHover: "#86efac",
  },
  warning: {
    base: "#f97316",
    hover: "#ea580c",
    active: "#c2410c",
    bg: "#fff7ed",
    bgHover: "#fed7aa",
    border: "#fdba74",
    borderHover: "#fb923c",
  },
  error: {
    base: "#ef4444",
    hover: "#dc2626",
    active: "#b91c1c",
    bg: "#fef2f2",
    bgHover: "#fecaca",
    border: "#fca5a5",
    borderHover: "#f87171",
  },
  overlay: {
    spotlight: "rgba(38, 38, 38, 0.85)",
    mask: "rgba(38, 38, 38, 0.45)",
  },
  shadow: {
    sm: "0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px -1px rgba(0, 0, 0, 0.1)",
    md: "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -2px rgba(0, 0, 0, 0.1)",
  },
} as const;

const neutral = shadcnPalette.zinc;

export const shadcnTheme: ThemeConfig = {
  algorithm: theme.defaultAlgorithm,
  token: {
    colorPrimary: neutral[800],
    colorSuccess: shadcnPalette.success.base,
    colorWarning: shadcnPalette.warning.base,
    colorError: shadcnPalette.error.base,
    colorInfo: neutral[800],
    colorTextBase: neutral[800],
    colorBgBase: shadcnPalette.white,
    colorPrimaryBg: neutral[100],
    colorPrimaryBgHover: neutral[200],
    colorPrimaryBorder: neutral[300],
    colorPrimaryBorderHover: neutral[400],
    colorPrimaryHover: neutral[700],
    colorPrimaryActive: neutral[900],
    colorPrimaryText: neutral[800],
    colorPrimaryTextHover: neutral[700],
    colorPrimaryTextActive: neutral[900],
    colorSuccessBg: shadcnPalette.success.bg,
    colorSuccessBgHover: shadcnPalette.success.bgHover,
    colorSuccessBorder: shadcnPalette.success.border,
    colorSuccessBorderHover: shadcnPalette.success.borderHover,
    colorSuccessHover: shadcnPalette.success.hover,
    colorSuccessActive: shadcnPalette.success.active,
    colorSuccessText: shadcnPalette.success.hover,
    colorSuccessTextHover: shadcnPalette.success.hover,
    colorSuccessTextActive: shadcnPalette.success.active,
    colorWarningBg: shadcnPalette.warning.bg,
    colorWarningBgHover: shadcnPalette.warning.bgHover,
    colorWarningBorder: shadcnPalette.warning.border,
    colorWarningBorderHover: shadcnPalette.warning.borderHover,
    colorWarningHover: shadcnPalette.warning.hover,
    colorWarningActive: shadcnPalette.warning.active,
    colorWarningText: shadcnPalette.warning.hover,
    colorWarningTextHover: shadcnPalette.warning.hover,
    colorWarningTextActive: shadcnPalette.warning.active,
    colorErrorBg: shadcnPalette.error.bg,
    colorErrorBgHover: shadcnPalette.error.bgHover,
    colorErrorBorder: shadcnPalette.error.border,
    colorErrorBorderHover: shadcnPalette.error.borderHover,
    colorErrorHover: shadcnPalette.error.hover,
    colorErrorActive: shadcnPalette.error.active,
    colorErrorText: shadcnPalette.error.hover,
    colorErrorTextHover: shadcnPalette.error.hover,
    colorErrorTextActive: shadcnPalette.error.active,
    colorInfoBg: neutral[100],
    colorInfoBgHover: neutral[200],
    colorInfoBorder: neutral[300],
    colorInfoBorderHover: neutral[400],
    colorInfoHover: neutral[700],
    colorInfoActive: neutral[900],
    colorInfoText: neutral[800],
    colorInfoTextHover: neutral[700],
    colorInfoTextActive: neutral[900],
    colorText: neutral[800],
    colorTextHeading: neutral[900],
    colorTextSecondary: neutral[600],
    colorTextTertiary: neutral[500],
    colorTextQuaternary: neutral[400],
    colorTextPlaceholder: neutral[400],
    colorTextDisabled: neutral[400],
    colorTextLightSolid: shadcnPalette.white,
    colorBgContainer: shadcnPalette.white,
    colorBgElevated: shadcnPalette.white,
    colorBgLayout: neutral[50],
    colorBgSpotlight: shadcnPalette.overlay.spotlight,
    colorBgMask: shadcnPalette.overlay.mask,
    colorBorder: neutral[200],
    colorBorderSecondary: neutral[100],
    colorFill: "rgba(24, 24, 27, 0.08)",
    colorFillSecondary: "rgba(24, 24, 27, 0.06)",
    colorFillTertiary: "rgba(24, 24, 27, 0.04)",
    colorFillQuaternary: neutral[50],
    controlItemBgHover: neutral[50],
    controlItemBgActive: neutral[100],
    controlOutline: "rgba(24, 24, 27, 0.2)",
    borderRadius: 10,
    borderRadiusXS: 2,
    borderRadiusSM: 6,
    borderRadiusLG: 14,
    padding: 16,
    paddingSM: 12,
    paddingLG: 24,
    margin: 16,
    marginSM: 12,
    marginLG: 24,
    fontFamily:
      '"Geist", "Geist Sans", "Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    boxShadow: shadcnPalette.shadow.sm,
    boxShadowSecondary: shadcnPalette.shadow.md,
    wireframe: false,
  },
  components: {
    Button: {
      primaryShadow: "none",
      defaultShadow: "none",
      dangerShadow: "none",
      colorPrimary: neutral[800],
      defaultBg: shadcnPalette.white,
      defaultColor: neutral[900],
      defaultBorderColor: neutral[200],
      defaultHoverBg: neutral[100],
      defaultHoverBorderColor: neutral[300],
      defaultHoverColor: neutral[900],
      defaultActiveBg: neutral[200],
      defaultActiveBorderColor: neutral[300],
      borderRadius: 6,
      fontWeight: 500,
    },
    Input: {
      activeShadow: "none",
      hoverBorderColor: neutral[400],
      activeBorderColor: neutral[900],
      borderRadius: 6,
    },
    InputNumber: {
      activeShadow: "none",
      hoverBorderColor: neutral[400],
      activeBorderColor: neutral[900],
      borderRadius: 6,
    },
    Select: {
      optionSelectedBg: neutral[100],
      optionActiveBg: neutral[50],
      optionSelectedFontWeight: 500,
      borderRadius: 6,
    },
    Segmented: {
      trackBg: neutral[100],
      itemSelectedBg: shadcnPalette.white,
      itemHoverBg: neutral[50],
      itemActiveBg: neutral[200],
    },
    Alert: {
      borderRadiusLG: 8,
    },
    Modal: {
      borderRadiusLG: 12,
    },
    Card: {
      borderRadiusLG: 12,
      boxShadow: shadcnPalette.shadow.sm,
    },
    Dropdown: {
      borderRadiusLG: 10,
      boxShadowSecondary: shadcnPalette.shadow.md,
    },
    Tooltip: {
      colorBgSpotlight: shadcnPalette.overlay.spotlight,
    },
    Progress: {
      defaultColor: neutral[900],
      remainingColor: neutral[100],
    },
    Steps: {
      iconSize: 32,
    },
    Switch: {
      trackHeight: 24,
      trackMinWidth: 44,
      innerMinMargin: 4,
      innerMaxMargin: 24,
    },
    Checkbox: {
      borderRadiusSM: 4,
    },
    Slider: {
      trackBg: neutral[100],
      trackHoverBg: neutral[200],
      handleSize: 18,
      handleSizeHover: 20,
      railSize: 6,
    },
    ColorPicker: {
      borderRadius: 6,
    },
  },
};
