import type { ThemeConfig } from "antdv-next";
import { theme } from "antdv-next";

export const shadcnPalette = {
  zinc: {
    50: "#fafafa",
    100: "#f4f4f5",
    200: "#e4e4e7",
    300: "#d4d4d8",
    400: "#a1a1aa",
    500: "#71717a",
    600: "#52525b",
    700: "#3f3f46",
    800: "#27272a",
    900: "#18181b",
  },
  white: "#ffffff",
  success: "#16a34a",
  warning: "#d97706",
  error: "#dc2626",
  shadow: {
    sm: "0 1px 2px rgba(24, 24, 27, 0.05)",
    md: "0 4px 12px rgba(24, 24, 27, 0.08)",
  },
} as const;

const neutral = shadcnPalette.zinc;

export const shadcnTheme: ThemeConfig = {
  algorithm: theme.defaultAlgorithm,
  token: {
    colorPrimary: neutral[900],
    colorSuccess: shadcnPalette.success,
    colorWarning: shadcnPalette.warning,
    colorError: shadcnPalette.error,
    colorInfo: neutral[900],
    colorTextBase: neutral[900],
    colorBgBase: shadcnPalette.white,
    colorPrimaryBg: neutral[100],
    colorPrimaryBgHover: neutral[200],
    colorPrimaryBorder: neutral[300],
    colorPrimaryBorderHover: neutral[400],
    colorPrimaryHover: neutral[800],
    colorPrimaryActive: "#09090b",
    colorPrimaryText: neutral[900],
    colorPrimaryTextHover: neutral[800],
    colorPrimaryTextActive: "#09090b",
    colorSuccessBg: "#f0fdf4",
    colorSuccessBgHover: "#dcfce7",
    colorSuccessBorder: "#bbf7d0",
    colorSuccessBorderHover: "#86efac",
    colorSuccessHover: "#15803d",
    colorSuccessActive: "#166534",
    colorSuccessText: "#15803d",
    colorSuccessTextHover: "#166534",
    colorSuccessTextActive: "#14532d",
    colorWarningBg: "#fffbeb",
    colorWarningBgHover: "#fef3c7",
    colorWarningBorder: "#fde68a",
    colorWarningBorderHover: "#fcd34d",
    colorWarningHover: "#b45309",
    colorWarningActive: "#92400e",
    colorWarningText: "#b45309",
    colorWarningTextHover: "#92400e",
    colorWarningTextActive: "#78350f",
    colorErrorBg: "#fef2f2",
    colorErrorBgHover: "#fee2e2",
    colorErrorBorder: "#fecaca",
    colorErrorBorderHover: "#fca5a5",
    colorErrorHover: "#b91c1c",
    colorErrorActive: "#991b1b",
    colorErrorText: "#b91c1c",
    colorErrorTextHover: "#991b1b",
    colorErrorTextActive: "#7f1d1d",
    colorInfoBg: neutral[100],
    colorInfoBgHover: neutral[200],
    colorInfoBorder: neutral[300],
    colorInfoBorderHover: neutral[400],
    colorInfoHover: neutral[800],
    colorInfoActive: "#09090b",
    colorInfoText: neutral[900],
    colorInfoTextHover: neutral[800],
    colorInfoTextActive: "#09090b",
    colorText: neutral[900],
    colorTextHeading: neutral[900],
    colorTextSecondary: neutral[600],
    colorTextTertiary: neutral[500],
    colorTextQuaternary: neutral[400],
    colorTextPlaceholder: neutral[400],
    colorTextDisabled: neutral[400],
    colorTextLightSolid: shadcnPalette.white,
    colorBgContainer: shadcnPalette.white,
    colorBgElevated: shadcnPalette.white,
    colorBgLayout: neutral[50],
    colorBgSpotlight: neutral[900],
    colorBgMask: "rgba(9, 9, 11, 0.45)",
    colorBorder: neutral[200],
    colorBorderSecondary: neutral[100],
    colorFill: "rgba(24, 24, 27, 0.08)",
    colorFillSecondary: "rgba(24, 24, 27, 0.06)",
    colorFillTertiary: "rgba(24, 24, 27, 0.04)",
    colorFillQuaternary: neutral[50],
    controlItemBgHover: neutral[50],
    controlItemBgActive: neutral[100],
    controlOutline: "rgba(24, 24, 27, 0.24)",
    borderRadius: 8,
    borderRadiusXS: 2,
    borderRadiusSM: 6,
    borderRadiusLG: 8,
    padding: 16,
    paddingSM: 12,
    paddingLG: 24,
    margin: 16,
    marginSM: 12,
    marginLG: 24,
    fontFamily:
      '"Geist", "Geist Sans", "Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
    boxShadow: shadcnPalette.shadow.sm,
    boxShadowSecondary: shadcnPalette.shadow.md,
    wireframe: false,
  },
  components: {
    Button: {
      primaryShadow: "none",
      defaultShadow: "none",
      dangerShadow: "none",
      colorPrimary: neutral[900],
      defaultBg: shadcnPalette.white,
      defaultColor: neutral[900],
      defaultBorderColor: neutral[200],
      defaultHoverBg: neutral[50],
      defaultHoverBorderColor: neutral[300],
      defaultHoverColor: neutral[900],
      defaultActiveBg: neutral[100],
      defaultActiveBorderColor: neutral[300],
      borderRadius: 6,
      fontWeight: 500,
    },
    Input: {
      activeShadow: "none",
      hoverBorderColor: neutral[400],
      activeBorderColor: neutral[900],
      borderRadius: 6,
    },
    InputNumber: {
      activeShadow: "none",
      hoverBorderColor: neutral[400],
      activeBorderColor: neutral[900],
      borderRadius: 6,
    },
    Select: {
      optionSelectedBg: neutral[100],
      optionActiveBg: neutral[50],
      optionSelectedFontWeight: 500,
      borderRadius: 6,
    },
    Segmented: {
      trackBg: neutral[100],
      itemSelectedBg: shadcnPalette.white,
      itemHoverBg: neutral[50],
      itemActiveBg: neutral[200],
    },
    Alert: { borderRadiusLG: 8 },
    Modal: { borderRadiusLG: 8 },
    Card: { borderRadiusLG: 8, boxShadow: shadcnPalette.shadow.sm },
    Dropdown: { borderRadiusLG: 8, boxShadowSecondary: shadcnPalette.shadow.md },
    Tooltip: { colorBgSpotlight: neutral[900] },
    Progress: { defaultColor: neutral[900], remainingColor: neutral[100] },
    Steps: { iconSize: 32 },
    Switch: { trackHeight: 24, trackMinWidth: 44, innerMinMargin: 4, innerMaxMargin: 24 },
    Checkbox: { borderRadiusSM: 4 },
    Slider: {
      trackBg: neutral[100],
      trackHoverBg: neutral[200],
      handleSize: 18,
      handleSizeHover: 20,
      railSize: 6,
    },
    ColorPicker: { borderRadius: 6 },
  },
};

export const shadcnDarkTheme: ThemeConfig = {
  ...shadcnTheme,
  algorithm: theme.darkAlgorithm,
  token: {
    ...shadcnTheme.token,
    colorPrimary: neutral[50],
    colorPrimaryBg: neutral[900],
    colorPrimaryBgHover: neutral[800],
    colorPrimaryBorder: neutral[700],
    colorPrimaryBorderHover: neutral[600],
    colorPrimaryHover: neutral[200],
    colorPrimaryActive: shadcnPalette.white,
    colorPrimaryText: neutral[50],
    colorPrimaryTextHover: neutral[200],
    colorPrimaryTextActive: shadcnPalette.white,
    colorInfo: neutral[50],
    colorInfoBg: neutral[900],
    colorInfoBgHover: neutral[800],
    colorInfoBorder: neutral[700],
    colorInfoBorderHover: neutral[600],
    colorInfoHover: neutral[200],
    colorInfoActive: shadcnPalette.white,
    colorInfoText: neutral[200],
    colorInfoTextHover: neutral[100],
    colorInfoTextActive: shadcnPalette.white,
    colorSuccessBg: "#052e16",
    colorSuccessBgHover: "#14532d",
    colorSuccessBorder: "#166534",
    colorSuccessBorderHover: "#15803d",
    colorSuccessText: "#86efac",
    colorSuccessTextHover: "#bbf7d0",
    colorSuccessTextActive: "#dcfce7",
    colorWarningBg: "#422006",
    colorWarningBgHover: "#713f12",
    colorWarningBorder: "#854d0e",
    colorWarningBorderHover: "#a16207",
    colorWarningText: "#fde68a",
    colorWarningTextHover: "#fef3c7",
    colorWarningTextActive: "#fffbeb",
    colorErrorBg: "#450a0a",
    colorErrorBgHover: "#7f1d1d",
    colorErrorBorder: "#991b1b",
    colorErrorBorderHover: "#b91c1c",
    colorErrorText: "#fca5a5",
    colorErrorTextHover: "#fecaca",
    colorErrorTextActive: "#fee2e2",
    colorTextBase: neutral[50],
    colorText: neutral[50],
    colorTextHeading: neutral[50],
    colorTextSecondary: neutral[300],
    colorTextTertiary: neutral[400],
    colorTextQuaternary: neutral[500],
    colorTextPlaceholder: neutral[400],
    colorTextDisabled: neutral[500],
    colorTextLightSolid: "#09090b",
    colorBgBase: "#09090b",
    colorBgContainer: "#09090b",
    colorBgElevated: neutral[900],
    colorBgLayout: "#09090b",
    colorBgSpotlight: neutral[50],
    colorBgMask: "rgba(0, 0, 0, 0.65)",
    colorBorder: neutral[800],
    colorBorderSecondary: neutral[900],
    colorFill: "rgba(250, 250, 250, 0.12)",
    colorFillSecondary: "rgba(250, 250, 250, 0.09)",
    colorFillTertiary: "rgba(250, 250, 250, 0.06)",
    colorFillQuaternary: neutral[900],
    controlItemBgHover: neutral[900],
    controlItemBgActive: neutral[800],
    controlOutline: "rgba(250, 250, 250, 0.24)",
    boxShadow: "0 1px 2px rgba(0, 0, 0, 0.35)",
    boxShadowSecondary: "0 12px 32px rgba(0, 0, 0, 0.48)",
  },
  components: {
    ...shadcnTheme.components,
    Button: {
      ...shadcnTheme.components?.Button,
      colorPrimary: neutral[50],
      defaultBg: "#09090b",
      defaultColor: neutral[50],
      defaultBorderColor: neutral[800],
      defaultHoverBg: neutral[900],
      defaultHoverBorderColor: neutral[700],
      defaultHoverColor: shadcnPalette.white,
      defaultActiveBg: neutral[800],
      defaultActiveBorderColor: neutral[700],
    },
    Input: {
      ...shadcnTheme.components?.Input,
      hoverBorderColor: neutral[600],
      activeBorderColor: neutral[50],
    },
    InputNumber: {
      ...shadcnTheme.components?.InputNumber,
      hoverBorderColor: neutral[600],
      activeBorderColor: neutral[50],
    },
    Select: {
      ...shadcnTheme.components?.Select,
      optionSelectedBg: neutral[800],
      optionActiveBg: neutral[900],
    },
    Segmented: {
      ...shadcnTheme.components?.Segmented,
      trackBg: neutral[900],
      itemSelectedBg: neutral[800],
      itemHoverBg: neutral[800],
      itemActiveBg: neutral[700],
    },
    Tooltip: { colorBgSpotlight: neutral[50], colorTextLightSolid: "#09090b" },
    Progress: { defaultColor: neutral[50], remainingColor: neutral[800] },
    Slider: {
      ...shadcnTheme.components?.Slider,
      trackBg: neutral[800],
      trackHoverBg: neutral[700],
    },
  },
};
